include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/l10n/*.dart"

linter:
  rules:
    constant_identifier_names: false
    directives_ordering: true
    sort_pub_dependencies: true
    prefer_single_quotes: true
