name: provd QA & sanity checks
on:
  pull_request:
    paths:
      - provd/**
jobs:
  go-sanity:
    name: "Go: Code sanity"
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y libpam-dev libglib2.0-dev gcc gettext
      - uses: actions/checkout@v4
      - name: Go code sanity check
        uses: canonical/desktop-engineering/gh-actions/go/code-sanity@main
        with:
          golangci-lint-configfile: ".golangci.yaml"
          tools-directory: "provd"
          working-directory: "provd"
      - name: Build cmd/authd with withexamplebroker tag
        run: |
          set -eu
          go build provd/cmd/provd

  go-tests:
    name: "Go: Tests"
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Run tests
        run: |
          set -eu

          cd provd
          go test -coverpkg=./... -coverprofile=/tmp/coverage.out -covermode=set ./... -shuffle=on
      - name: Run tests (with race detector)
        run: |

          cd provd
          go test -race ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: /tmp/coverage.combined
