name: provd QA & sanity checks
on:
  pull_request:
    paths:
      - provd/**
env:
  apt_deps: >-
    libglib2.0-dev
    gcc
    gettext
    libpam0g-dev
jobs:
  go-sanity:
    name: "Go: Code sanity"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y ${{ env.apt_deps }}
      - uses: actions/checkout@v4
      - name: Go code sanity check
        uses: canonical/desktop-engineering/gh-actions/go/code-sanity@main
        with:
          golangci-lint-configfile: ".golangci.yaml"
          tools-directory: "./provd/tools"
          working-directory: "./provd"
      - name: Build cmd/provd
        run: |
          set -eu
          cd provd
          go build ./cmd/provd

  go-tests:
    name: "Go: Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./provd/go.mod"

      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y ${{ env.apt_deps }}
      - name: Run tests
        run: |
          set -eu

          cd provd
          go test -coverpkg=./... -coverprofile=/tmp/coverage.out -covermode=set ./... -shuffle=on
      - name: Run tests (with race detector)
        run: |

          cd provd
          go test -race ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: /tmp/coverage.combined
