name: Sync GitHub issues to Jira
on: [issues, issue_comment]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: [self-hosted, Linux, x64]
    steps:
      - uses: canonical/sync-issues-github-jira@v1
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
          component: 'S-Flutter'
